apiVersion: apps/v1
kind: Deployment
metadata:
  name: boxfuse-deployment
  labels:
    app: boxfuse-deployment
spec:
  containers:
      - name: boxfuse
        image: ashutoshteknur21/assignment2
    
