apiVersion: apps/v1
kind: Deployment
metadata:
  name: boxfuse-deployment
  labels:
    app: boxfuse-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boxfuse
  template:
    metadata:
      labels:
        app: boxfuse
  spec:
    containers:
        - name: boxfuse
          image: ashutoshteknur21/assignment2
    
